### ISSUE TITLE
WSOD when selecting a NHC track layer (v0.2.24)

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI/TerriaMap#66]
i am getting the white screen of death when i select a layer. here are the steps to reproduce:
 - open the filter dialog
 - hit the search button for tropical runs (no other filter selections made)
 - select the nhc forecast track shown in the results.
 - bam.

this could be a data related issue.

if you select a nhc forecast track along with another layer everything appears ok.

**Comment by lstillwe** [comment]
Some of the older Hurricane layers - retrieved from the RSS feed for the V1 UI are not compatible with the new UI. For instance, they don't have required fields for Naming the layer - which is causing the WSOD in this case. I guess I can put checks in the new either to make these layers selectable, or just add checks for all the fields used to label the data and leave them blank if they don't exist. Maybe both - because these RSS feed hurricane layers are not really meant for the new UI. Any comments on how to handle @scrummish or @PhillipsOwen? Thanks!

**Comment by PhillipsOwen** [comment]
Should they just be removed from the catalog data?

**Comment by lstillwe** [comment]
@PhillipsOwen - No, I don't think so. Added some code to the UI so that at least it doesn't crash anymore. But the layer will be added without any details in the layer card. Don't know if I want to upgrade load-geo to include that info for these layers in the new V2 UI, because they are really not supposed to be used/needed in the V2 UI, which uses MetGet to retrieve hurricane layer info. They only still exist in the DB for use in the old V1 UI, which Rick L. still seems to prefer. Let's discuss in the UI meeting today, and I will transfer those notes here. (Included screenshot of RSS feed based hurricane layer on V2 UI.)
![Screen Shot 2023-09-12 at 9 23 07 AM](https://github.com/RENCI/TerriaMap/assets/1794116/68844426-a308-4d1f-a5c8-9cdb48f026b1)

**Comment by lstillwe** [comment]
After discussion at today's UI meeting we decided to update the filtering code to require the user to select at least 1 search criteria on the tropical and synoptic tabs. This will eliminate the old hurricane layers from appearing in the V2 UI searches. Phil and I will do further testing on this once this change in made. Assigning to @scrummish

**Comment by scrummish** [comment]
@PhillipsOwen @lstillwe the forms are set to no longer create requests unless at least one field has been selected. This issue is ready to be tested and closed. (upgrade/form-filter)

**Comment by PhillipsOwen** [comment]
i see that there are some missing updates that were merged with develop that arent in the upgrade/form-filter branch. namely, there was an update to config.json for the "issues #87" branch merge.

i suspect there may be a possibility that other things are lurking in there. please pull/merge the latest from develop into your upgrade/form-filter branch and retest.

**Comment by PhillipsOwen** [comment]
please consider a warning message to the user that they need to supply at least one filter criteria to return results. 

otherwise this looks good to me.

**Comment by lstillwe** [comment]
All works okay ... closing
